[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ACCS-WP5"
authors = [{name = "Prodipta Guha", email = "prodipta.guha@unimelb.edu.au"}]
dynamic = ["version", "description"]
